window.ZH_PRODUCTS=[
{id:"p1",cat:"ChatGPT",tag:"本周爆款",name:"ChatGPT Plus 月卡｜菲律宾正规卡充（同步官方售后）",sub:"充值到自己账号",desc:"自助充值卡密，兑换后订阅一个月 Plus。",price:118,sold:604,stock:"即将售罄",delivery:"自动发货",tone:"blue"},
{id:"p2",cat:"ChatGPT",tag:"iOS充值",name:"ChatGPT Plus 月卡｜iOS 官方正规充值〖质保30天〗〖秒冲〗〖卡密可囤三天〗",sub:"充值到自己账号",desc:"iOS 场景的 ChatGPT Plus 月卡。",price:132,sold:4955,stock:"充足",delivery:"自动发货",tone:"blue"},
{id:"p3",cat:"ChatGPT",tag:"iOS充值",name:"ChatGPT Pro 5X｜1个月｜iOS 官方正规充值〖秒冲〗〖质保30天〗",sub:"5X-100刀款 · 充值自己账号",desc:"面向高频用户的 Pro 5X 方案。",price:650,sold:417,stock:"即将售罄",delivery:"自动发货",tone:"violet"},
{id:"p4",cat:"ChatGPT",tag:"推理强",name:"ChatGPT Pro 20X 月卡｜官方卡充｜1个月｜支持续费｜正规充值",sub:"20X-200刀款 · 充值自己账号",desc:"面向重度连续任务的 Pro 20X 方案。",price:1100,sold:564,stock:"即将售罄",delivery:"自动发货",tone:"violet"},
{id:"p5",cat:"ChatGPT",tag:"iOS充值",name:"ChatGPT Pro 20X｜1个月｜iOS 官方正规充值〖秒冲〗〖质保30天〗",sub:"20X-200刀款 · 充值自己账号",desc:"iOS 场景的 Pro 20X 充值方案。",price:1190,sold:135,stock:"即将售罄",delivery:"自动发货",tone:"violet"},
{id:"p6",cat:"Claude",tag:"Claude",name:"Claude Pro 月卡｜IOS官方正规充值〖秒冲〗〖质保30天〗",sub:"充值到自己账号",desc:"适合长文本、写作、翻译与复杂分析。",price:136,sold:812,stock:"即将售罄",delivery:"自动发货",tone:"amber"},
{id:"p7",cat:"Grok",tag:"Grok",name:"Grok Super 月卡｜IOS官方正规充值〖质保订阅〗",sub:"充值到自己账号",desc:"Grok Super 月卡。",price:260,sold:284,stock:"即将售罄",delivery:"自动发货",tone:"silver"},
{id:"p8",cat:"Gemini",tag:"Gemini设计向",name:"Gemini Pro 12个月成品〖质保首登丨官方订阅〗美区高权重账号",sub:"成品号",desc:"Gemini Pro 一年成品账号方案。",price:35,sold:189,stock:"即将售罄",delivery:"自动发货",tone:"green"},
{id:"p9",cat:"Binance",tag:"人工核单",name:"币安广场刷粉业务",sub:"刷粉业务",desc:"平台增长类人工服务。",price:400,sold:6,stock:"即将售罄",delivery:"人工核单发货",tone:"gold"},
{id:"p10",cat:"API / 中转",tag:"API",name:"AI API / 中转服务",sub:"接口服务 · 按量使用",desc:"开发者 API / 中转服务入口，具体模型与额度以实际配置为准。",price:0,sold:0,stock:"联系客服",delivery:"人工核单发货",tone:"cyan"}
];
window.ZH_CATS=["全部","ChatGPT","Claude","Gemini","Grok","API / 中转","Binance"];
window.ZH_GUIDES=[
"ChatGPT Plus 购买完整教程：选商品、下单、付款与查收",
"ChatGPT 充值完整教程：购买、付款、查单与交付流程",
"AI 模型版本与使用指南：如何按任务选择",
"OpenAI Codex 完整指南：App、Cloud、CLI 与 IDE",
"幸运抽奖机会获取说明",
"AI 会员套餐怎么选：ChatGPT、Claude、Gemini 与 Grok",
"支付成功但订单没变化：状态与回调排查",
"自动发货与游客查单教程",
"AI 会员账号安全清单",
"AI 会员充值不到账排查",
"Codex 使用前怎么选订阅",
"ChatGPT 充值自助排查：支付、到账、账号与网络",
"ChatGPT 充值常见问题 FAQ",
"模型升级、续费与模型列表排查",
"ChatGPT 付款未获批准怎么办",
"ChatGPT Pro 订阅指南",
"ChatGPT Plus / Pro 怎么选",
"ChatGPT 充值到账延迟怎么办",
"新模型能力与使用指南",
"ChatGPT 注册教程：邮箱注册、登录与错误排查",
"AI 生图与局部编辑使用指南",
"专业工作、Agent 与 Codex 场景指南",
"ChatGPT 回答质量下降怎么办",
"回答质量下降完整排查",
"ChatGPT 网络环境检测",
"IP、设备与账号风控原理",
"住宅 IP 与稳定网络选择原则",
"图像模型精准编辑回顾",
"旧版模型能力回顾与升级路径",
"ChatGPT Plus 国内升级指南",
"ChatGPT Plus 适合谁",
"ChatGPT Pro 适合谁",
"ChatGPT Plus 与 Business 怎么选",
"Grok / SuperGrok 订阅指南",
"Google Gemini 订阅指南",
"ChatGPT 套餐与价格比较方法"
];
window.ZH_FAQ=[
["购买前应该先看什么？","先看商品详情页里的适用范围、库存、价格、交付方式和售后规则。"],
["价格和库存会变化吗？","会，以下单时页面显示为准。"],
["智核商店是官方官网吗？","不是，智核商店是独立第三方平台。"],
["Plus 和 Pro 怎么选？","日常使用先看 Plus，高频再看 Pro 5X，重度任务再考虑 20X。"],
["自动发货是什么意思？","付款确认后按商品规则处理，并把交付内容同步到订单详情。"],
["订单在哪里查询？","可以使用订单号、邮箱或手机号与查询密码。"],
["充值不到账怎么办？","先查订单状态和支付记录，再按商品规则提交售后。"],
["怎么联系客服？","进入客服或提交工单页面，并附订单号和必要截图。"],
["能把第三方账号密码发给客服吗？","不要发送密码、验证码、Cookie、Session、Token 或钱包私钥。"]
];