const API=(location.hostname==="localhost"||location.hostname==="127.0.0.1")?"http://localhost:8787":"https://api.zhihebot.shop";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>x.classList.remove("show"),2200)}
async function api(path,opt={}){const r=await fetch(API+path,{credentials:"include",...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"请求失败");return d}
function preview(id,url){const x=$("#"+id);x.innerHTML=url?'<img class="preview" src="'+esc(url)+'">':""}
function show(app){$("#login").classList.toggle("hide",app);$("#app").classList.toggle("hide",!app)}
async function check(){try{const d=await api("/admin/me");if(d.authenticated){show(true);await boot();}else show(false)}catch{show(false)}}
$("#loginBtn").onclick=async()=>{const msg=$("#loginMsg");msg.textContent="";try{await api("/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("#password").value})});show(true);await boot();}catch(e){msg.textContent=e.message}}
$("#logout").onclick=async()=>{try{await api("/admin/logout",{method:"POST"})}finally{show(false)}};
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.toggle("active",x===b));$$(".section").forEach(x=>x.classList.toggle("active",x.id===b.dataset.tab));if(b.dataset.tab==="orders")loadOrders();if(b.dataset.tab==="products")loadProducts();if(b.dataset.tab==="payments")loadPayments();if(b.dataset.tab==="site")loadSite()});
async function loadDashboard(){const d=await api("/admin/dashboard");$("#stats").innerHTML=[["订单总数",d.totalOrders],["待处理",d.pendingOrders],["已付款",d.paidOrders],["已完成",d.completedOrders],["已付款金额","¥"+Number(d.revenue||0).toFixed(2)]].map(x=>'<div class="card stat"><small>'+x[0]+'</small><strong>'+x[1]+'</strong></div>').join("");$("#dashText").textContent="后台运行正常。支付设置、商品和订单均由 Cloudflare Worker + D1 管理。"}
function productForm(p={}){const data={id:"",name:"",category:"ChatGPT",tag:"",subtitle:"",price:0,sold:0,stock:0,delivery:"自动发货",tone:"blue",detail:"",imageUrl:"",enabled:true,...p};$("#productForm").classList.remove("hide");$("#productForm").innerHTML='<h3>'+ (data.id?"编辑商品":"新增商品")+'</h3><div class="two grid"><label>商品名称<input id="pf_name" class="input" value="'+esc(data.name)+'"></label><label>分类<input id="pf_category" class="input" value="'+esc(data.category)+'"></label><label>标签<input id="pf_tag" class="input" value="'+esc(data.tag)+'"></label><label>副标题<input id="pf_subtitle" class="input" value="'+esc(data.subtitle)+'"></label><label>价格<input id="pf_price" class="input" type="number" step="0.01" value="'+data.price+'"></label><label>库存<input id="pf_stock" class="input" type="number" value="'+data.stock+'"></label><label>销量<input id="pf_sold" class="input" type="number" value="'+data.sold+'"></label><label>交付方式<input id="pf_delivery" class="input" value="'+esc(data.delivery)+'"></label></div><div class="field"><label>商品详情<textarea id="pf_detail" class="input" rows="4">'+esc(data.detail)+'</textarea></label></div><label><input id="pf_enabled" type="checkbox" '+(data.enabled?"checked":"")+'> 上架</label><div class="row" style="margin-top:12px"><button class="btn primary" id="pf_save">保存</button><button class="btn ghost" id="pf_cancel">取消</button></div>';$("#pf_cancel").onclick=()=>$("#productForm").classList.add("hide");$("#pf_save").onclick=async()=>{const body={id:data.id||crypto.randomUUID(),name:$("#pf_name").value,category:$("#pf_category").value,tag:$("#pf_tag").value,subtitle:$("#pf_subtitle").value,price:Number($("#pf_price").value||0),stock:Number($("#pf_stock").value||0),sold:Number($("#pf_sold").value||0),delivery:$("#pf_delivery").value,tone:data.tone,detail:$("#pf_detail").value,enabled:$("#pf_enabled").checked};try{await api(data.id?"/admin/products/"+encodeURIComponent(data.id):"/admin/products",{method:data.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});toast("商品已保存");$("#productForm").classList.add("hide");loadProducts();loadDashboard();}catch(e){toast(e.message)}}}
async function loadProducts(){const d=await api("/admin/products");$("#productList").innerHTML='<table class="table"><thead><tr><th>商品</th><th>分类</th><th>价格</th><th>库存</th><th>状态</th><th>操作</th></tr></thead><tbody>'+d.products.map(p=>'<tr><td><b>'+esc(p.name)+'</b><br><span class="hint">'+esc(p.subtitle)+'</span></td><td>'+esc(p.category)+'</td><td>¥'+Number(p.price).toFixed(2)+'</td><td>'+p.stock+'</td><td>'+(p.enabled?'<span class="status">上架</span>':'<span class="danger">下架</span>')+'</td><td><button class="btn ghost" data-edit="'+esc(p.id)+'">编辑</button> <button class="btn ghost danger" data-del="'+esc(p.id)+'">删除</button></td></tr>').join("")+'</tbody></table>';$$("[data-edit]").forEach(b=>b.onclick=()=>productForm(d.products.find(p=>p.id===b.dataset.edit)));$$("[data-del]").forEach(b=>b.onclick=async()=>{if(!confirm("确定删除这个商品吗？"))return;try{await api("/admin/products/"+encodeURIComponent(b.dataset.del),{method:"DELETE"});toast("已删除");loadProducts();}catch(e){toast(e.message)}})}
async function loadOrders(){const d=await api("/admin/orders");$("#orderList").innerHTML='<table class="table"><thead><tr><th>订单</th><th>商品</th><th>金额</th><th>付款</th><th>状态</th><th>交付内容</th></tr></thead><tbody>'+d.orders.map(o=>'<tr><td><b>'+esc(o.id)+'</b><br>'+esc(o.created_at)+'</td><td>'+esc(o.product_name||o.product_id)+'</td><td>¥'+Number(o.total).toFixed(2)+'</td><td>'+esc(o.payment_method||"未选择")+'<br>'+esc(o.payment_status||"")+'</td><td><select class="input" style="min-width:120px" data-status="'+esc(o.id)+'"><option '+(o.status==="待付款"?"selected":"")+' >待付款</option><option '+(o.status==="待处理"?"selected":"")+'>待处理</option><option '+(o.status==="已发货"?"selected":"")+'>已发货</option><option '+(o.status==="已完成"?"selected":"")+'>已完成</option><option '+(o.status==="已取消"?"selected":"")+'>已取消</option></select><br><select class="input" style="min-width:120px" data-payment="'+esc(o.id)+'"><option '+(o.payment_status==="待选择支付方式"?"selected":"")+'>待选择支付方式</option><option '+(o.payment_status==="待付款"?"selected":"")+'>待付款</option><option '+(o.payment_status==="已付款"?"selected":"")+'>已付款</option></select></td><td><textarea class="input" rows="2" data-delivery="'+esc(o.id)+'">'+esc(o.delivery_content||"")+'</textarea><button class="btn primary" data-saveorder="'+esc(o.id)+'">保存</button></td></tr>').join("")+'</tbody></table>';$$("[data-saveorder]").forEach(b=>b.onclick=async()=>{const id=b.dataset.saveorder;try{await api("/admin/orders/"+encodeURIComponent(id),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:document.querySelector('[data-status="'+id+'"]').value,paymentStatus:document.querySelector('[data-payment="'+id+'"]').value,deliveryContent:document.querySelector('[data-delivery="'+id+'"]').value})});toast("订单已更新");loadDashboard();}catch(e){toast(e.message)}})}
async function upload(file,slot){if(!file)return "";const fd=new FormData();fd.append("file",file);fd.append("slot",slot);return (await api("/admin/upload",{method:"POST",body:fd})).url}
async function loadPayments(){const d=await api("/admin/settings");const p=d.payments||{},a=p.alipay1||{},a2=p.alipay2||{},w=p.wechat||{},u=p.usdt||{};$("#alipay1Enabled").checked=!!a.enabled;$("#alipay1Code").value=a.pureCode||"";$("#alipay1Button").value=a.buttonText||"打开支付宝立即支付";$("#alipay1Link").textContent=a.deepLink||"填写纯净码后生成";preview("alipay1Qr",a.qrUrl);$("#alipay2Enabled").checked=!!a2.enabled;$("#alipay2Link").value=a2.link||"";$("#alipay2Button").value=a2.buttonText||"支付宝2支付";preview("alipay2Qr",a2.qrUrl);$("#wechatEnabled").checked=!!w.enabled;$("#wechatButton").value=w.buttonText||"请打开微信扫一扫支付";preview("wechatQr",w.qrUrl);$("#usdtEnabled").checked=!!u.enabled;$("#usdtNetwork").value=u.network||"TRC20";$("#usdtAddress").value=u.address||"";preview("usdtQr",u.qrUrl)}
$("#alipay1Code").oninput=()=>$("#alipay1Link").textContent=$("#alipay1Code").value.trim()?"将在保存后由服务器生成":"填写纯净码后生成";
$("#savePayments").onclick=async()=>{try{let d=await api("/admin/settings"),p=d.payments||{};p.alipay1={...(p.alipay1||{}),enabled:$("#alipay1Enabled").checked,pureCode:$("#alipay1Code").value.trim(),buttonText:$("#alipay1Button").value.trim()||"打开支付宝立即支付"};p.alipay2={...(p.alipay2||{}),enabled:$("#alipay2Enabled").checked,link:$("#alipay2Link").value.trim(),buttonText:$("#alipay2Button").value.trim()||"支付宝2支付"};p.wechat={...(p.wechat||{}),enabled:$("#wechatEnabled").checked,buttonText:$("#wechatButton").value.trim()||"请打开微信扫一扫支付"};p.usdt={...(p.usdt||{}),enabled:$("#usdtEnabled").checked,network:$("#usdtNetwork").value.trim(),address:$("#usdtAddress").value.trim()};const uploads=[["alipay1File","alipay1_qr"],["alipay2File","alipay2_qr"],["wechatFile","wechat_qr"],["usdtFile","usdt_qr"]];for(const [id,slot] of uploads){const f=$("#"+id).files[0];if(f){const url=await upload(f,slot);if(slot==="alipay1_qr")p.alipay1.qrUrl=url;if(slot==="alipay2_qr")p.alipay2.qrUrl=url;if(slot==="wechat_qr")p.wechat.qrUrl=url;if(slot==="usdt_qr")p.usdt.qrUrl=url;}}await api("/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({payments:p})});toast("支付设置已保存");loadPayments();}catch(e){toast(e.message)}};
async function loadSite(){const d=await api("/admin/settings"),s=d.site||{};$("#siteName").value=s.siteName||"智核商店";$("#siteSubtitle").value=s.siteSubtitle||"";$("#announcementText").value=s.announcementText||"";$("#telegramUrl").value=s.telegramUrl||"";$("#popupTitle").value=s.popupTitle||"";$("#popupContent").value=s.popupContent||"";$("#popupNotice").value=s.popupNotice||""}
$("#saveSite").onclick=async()=>{try{const d=await api("/admin/settings"),s=d.site||{};Object.assign(s,{siteName:$("#siteName").value.trim(),siteSubtitle:$("#siteSubtitle").value.trim(),announcementText:$("#announcementText").value.trim(),telegramUrl:$("#telegramUrl").value.trim(),popupTitle:$("#popupTitle").value.trim(),popupContent:$("#popupContent").value.trim(),popupNotice:$("#popupNotice").value.trim()});await api("/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({site:s})});toast("网站设置已保存")}catch(e){toast(e.message)}};
$("#newProduct").onclick=()=>productForm();$("#refreshOrders").onclick=loadOrders;
async function boot(){await loadDashboard();await loadPayments();await loadSite()}
check();
