name = "zhihebot-api"
main = "src/index.js"
compatibility_date = "2026-10-06"

[vars]
FRONTEND_ORIGIN = "https://zhihebot.shop"

[[d1_databases]]
binding = "DB"
database_name = "zhihebot"
database_id = "6bca47f3-6f47-42c5-8d6c-4392ff692633"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "zhihebot-assets"
